server:
  port: ${PORT:8080}

file:
  upload-dir: src/main/resources/static/uploads

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  token-prefix: Bearer
  header: Authorization

logging:
  level:
    com.ghr360: DEBUG
    org.springframework.security: DEBUG

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}
  folder: ghr360
